clientes/urls.py
from django.urls import path
from .views import (
    cliente_views,
    pet_views,
    consulta_views,
    funcionario_views,
    autenticacao_views,
)

urlpatterns = [
    path(
        "cadastrar_cliente", cliente_views.cadastrar_cliente, name="cadastrar_cliente"
    ),
    path("listar_clientes", cliente_views.listar_clientes, name="listar_clientes"),
    path(
        "lista_cliente/<int:id>",
        cliente_views.listar_cliente_id,
        name="listar_cliente_id",
    ),
    path(
        "editar_cliente/<int:id>", cliente_views.editar_cliente, name="editar_cliente"
    ),
    path(
        "remover_cliente/<int:id>",
        cliente_views.remover_cliente,
        name="remover_cliente",
    ),
    path("cadastrar_pet/<int:id>", pet_views.inserir_pet, name="cadastrar_pet"),
    path("listar_pet/<int:id>", pet_views.listar_pet_id, name="listar_pet_id"),
    path(
        "cadastrar_consulta/<int:id>",
        consulta_views.inserir_consulta,
        name="cadastrar_consulta",
    ),
    path(
        "lista_consulta/<int:id>",
        consulta_views.listar_consulta_id,
        name="listar_consulta_id",
    ),
    path(
        "enviar_consulta/<int:id>",
        consulta_views.enviar_email_consulta,
        name="enviar_consulta",
    ),
    path(
        "cadastrar_funcionario",
        funcionario_views.inserir_funcionario,
        name="cadastrar_funcionario",
    ),
    path(
        "listar_funcionarios",
        funcionario_views.listar_funcionarios,
        name="listar_funcionarios",
    ),
    path("login", autenticacao_views.login_usuario, name="login_usuario"),
    path("logout", autenticacao_views.deslogar_usuario, name="deslogar_usuario"),
    
]

setup/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("clientes/", include("clientes.urls")),
]

clientes/models.py
from django.db import models
from localflavor.br.br_states import STATE_CHOICES
from django.contrib.auth.models import AbstractUser


class EnderecoCliente(models.Model):
    rua = models.CharField(max_length=50, null=False, blank=False)
    cidade = models.CharField(max_length=30, null=False, blank=False)
    estado = models.CharField(
        max_length=2, choices=STATE_CHOICES, null=False, blank=False
    )


class Cliente(models.Model):
    nome = models.CharField(max_length=100, null=False, blank=False)
    email = models.EmailField(null=False, blank=False)
    endereco = models.ForeignKey(EnderecoCliente, on_delete=models.CASCADE)
    cpf = models.CharField(max_length=14, null=False, blank=False)
    data_nascimento = models.DateField(null=False, blank=False)
    profissao = models.CharField(max_length=25, null=False, blank=False)


class Pet(models.Model):
    CATEGORIA_PET_CHOICES = (
        ("Ca", "Cachorro"),
        ("Ga", "Gato"),
        ("Co", "Coelho"),
    )

    COR_PET_CHOICES = (
        ("Pr", "Preto"),
        ("Br", "Branco"),
        ("Ci", "Cinza"),
        ("Ma", "Marrom"),
    )
    nome = models.CharField(max_length=50, null=False, blank=False)
    nascimento = models.DateField(null=False, blank=False)
    categoria = models.CharField(
        max_length=2, choices=CATEGORIA_PET_CHOICES, null=False, blank=False
    )
    cor = models.CharField(
        max_length=2, choices=COR_PET_CHOICES, null=False, blank=False
    )
    dono = models.ForeignKey(Cliente, on_delete=models.CASCADE, null=False, blank=False)


class ConsultaPet(models.Model):
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE, null=False, blank=False)
    data = models.DateField(null=False, blank=False, auto_now_add=True)
    motivo_consulta = models.CharField(max_length=200, null=False, blank=False)
    peso_atual = models.FloatField(null=False, blank=False)
    medicamento_atual = models.TextField(null=False, blank=True)
    medicamentos_prescritos = models.TextField(null=False, blank=True)
    exames_prescritos = models.TextField(null=False, blank=True)


class Funcionario(AbstractUser):
    CARGO_CHOICES = [
        (1, "Veterinario"),
        (2, "Financeiro"),
        (3, "Atendimento"),
    ]
    nome = models.CharField(max_length=50, null=False, blank=False)
    nascimento = models.DateField(null=False, blank=False)
    cargo = models.IntegerField(choices=CARGO_CHOICES, null=False, blank=False)

clientes/forms/cliente_forms.py
from django import forms
from django.forms import TextInput, DateInput

from ..models import Cliente


class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ["nome", "email", "data_nascimento", "cpf", "profissao"]
        widgets = {"data_nascimento": DateInput(attrs={"type": "date"})}

clientes/forms/consulta_forms.py
from django import forms
from ..models import ConsultaPet


class ConsultaPetForm(forms.ModelForm):
    class Meta:
        model = ConsultaPet
        fields = "__all__"
        exclude = ["pet", "data"]

clientes/forms/endereco_forms.py
from django import forms

from ..models import EnderecoCliente


class EnderecoClienteForm(forms.ModelForm):
    class Meta:
        model = EnderecoCliente
        fields = ["rua", "cidade", "estado"]

clientes/forms/funcionario_forms.py
from django import forms
from django.forms import DateInput
from django.contrib.auth.forms import UserCreationForm
from ..models import Funcionario


class FuncionarioForm(UserCreationForm):
    class Meta:
        model = Funcionario
        fields = UserCreationForm.Meta.fields + ("nome", "nascimento", "cargo")
        widgets = {"nascimento": DateInput(attrs={"type": "date"})}

clientes/forms/pet_forms.py
from django import forms
from ..models import Pet


class PetForm(forms.ModelForm):
    class Meta:
        model = Pet
        fields = ["nome", "nascimento", "categoria", "cor"]
        exclude = [
            "dono",
        ]

clientes/views/autenticacao_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def login_usuario(request):
    if request.method == "POST":
        form_login = AuthenticationForm(data=request.POST)
        if form_login.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            usuario = authenticate(request, username=username, password=password)
            if usuario is not None:
                login(request, usuario)
                return redirect("listar_clientes")
            else:
                messages.error(request, "as credencias do usuário estçao incorretas")
                return redirect("login")

    else:
        form_login = AuthenticationForm()
    return render(request, "autenticacao/login.html", {"form_login": form_login})


def deslogar_usuario(request):
    logout(request)
    return redirect("login_usuario")

clientes/views/cliente_views.py
import datetime

from django.shortcuts import render, redirect
from ..forms.cliente_forms import ClienteForm
from ..forms.endereco_forms import EnderecoClienteForm
from ..entidades import cliente, endereco
from ..services import cliente_service, endereco_service, pet_service, consulta_service
from django.contrib.auth.decorators import login_required


@login_required()
def listar_clientes(request):
    clientes = cliente_service.listar_clientes()
    return render(request, "clientes/lista_clientes.html", {"clientes": clientes})


@login_required()
def listar_cliente_id(request, id):
    cliente = cliente_service.listar_cliente_id(id)
    pets = pet_service.listar_pets(id)
    consultas = consulta_service.listar_consultas_pets(id)
    return render(
        request,
        "clientes/lista_cliente.html",
        {"cliente": cliente, "pets": pets, "consultas": consultas},
    )


@login_required()
def remover_cliente(request, id):
    cliente = cliente_service.listar_cliente_id(id)
    endereco = endereco_service.listar_endereco_id(cliente.endereco.id)
    if request.method == "POST":
        cliente_service.remover_cliente(cliente)
        endereco_service.remover_endereco(endereco)
        return redirect("listar_clientes")
    return render(request, "clientes/confirma_exclusao.html", {"cliente": cliente})


@login_required()
def editar_cliente(request, id):
    cliente_editar = cliente_service.listar_cliente_id(id)
    cliente_editar.data_nascimento = cliente_editar.data_nascimento.strftime("%Y-%m-%d")
    form_cliente = ClienteForm(request.POST or None, instance=cliente_editar)
    endereco_editar = endereco_service.listar_endereco_id(cliente_editar.endereco.id)
    form_endereco = EnderecoClienteForm(request.POST or None, instance=endereco_editar)
    if form_cliente.is_valid():
        nome = form_cliente.cleaned_data["nome"]
        email = form_cliente.cleaned_data["email"]
        cpf = form_cliente.cleaned_data["cpf"]
        data_nascimento = form_cliente.cleaned_data["data_nascimento"]
        profissao = form_cliente.cleaned_data["profissao"]
        if form_endereco.is_valid():
            rua = form_endereco.cleaned_data["rua"]
            cidade = form_endereco.cleaned_data["cidade"]
            estado = form_endereco.cleaned_data["estado"]
            endereco_novo = endereco.Endereco(rua=rua, cidade=cidade, estado=estado)
            endereco_editado = endereco_service.editar_endereco(
                endereco_editar, endereco_novo
            )
            cliente_novo = cliente.Cliente(
                nome=nome,
                email=email,
                data_nascimento=data_nascimento,
                profissao=profissao,
                cpf=cpf,
                endereco=endereco_editado,
            )
            cliente_service.editar_cliente(cliente_editar, cliente_novo)
            return redirect("listar_clientes")
    return render(
        request,
        "clientes/form_cliente.html",
        {"form_cliente": form_cliente, "form_endereco": form_endereco},
    )


@login_required()
def cadastrar_cliente(request):
    if request.method == "POST":

        form_cliente = ClienteForm(request.POST)
        form_endereco = EnderecoClienteForm(request.POST)
        if form_cliente.is_valid():

            nome = form_cliente.cleaned_data["nome"]
            email = form_cliente.cleaned_data["email"]
            cpf = form_cliente.cleaned_data["cpf"]
            data_nascimento = form_cliente.cleaned_data["data_nascimento"]
            profissao = form_cliente.cleaned_data["profissao"]

            if form_endereco.is_valid():
                rua = form_endereco.cleaned_data["rua"]
                cidade = form_endereco.cleaned_data["cidade"]
                estado = form_endereco.cleaned_data["estado"]
                endereco_novo = endereco.Endereco(rua=rua, cidade=cidade, estado=estado)
                endereco_bd = endereco_service.cadastrar_endereco(endereco_novo)
                cliente_novo = cliente.Cliente(
                    nome=nome,
                    email=email,
                    data_nascimento=data_nascimento,
                    profissao=profissao,
                    cpf=cpf,
                    endereco=endereco_bd,
                )
                cliente_service.cadastrar_cliente(cliente_novo)
                return redirect("listar_clientes")
    else:

        form_cliente = ClienteForm()
        form_endereco = EnderecoClienteForm()
    return render(
        request,
        "clientes/form_cliente.html",
        {"form_cliente": form_cliente, "form_endereco": form_endereco},
    )

clientes/views/consulta_views.py
from django.shortcuts import redirect, render

from ..forms import consulta_forms
from ..services import pet_service, consulta_service
from ..entidades import consulta
from django.contrib.auth.decorators import login_required, user_passes_test
from django.template.loader import render_to_string
from django.core.mail import send_mail


@user_passes_test(lambda u: u.cargo == 1)
def inserir_consulta(request, id):
    if request.method == "POST":
        form_consulta = consulta_forms.ConsultaPetForm(request.POST)
        pet = pet_service.listar_pet_id(id)
        if form_consulta.is_valid():
            motivo_consulta = form_consulta.cleaned_data["motivo_consulta"]
            peso_atual = form_consulta.cleaned_data["peso_atual"]
            medicamento_atual = form_consulta.cleaned_data["medicamento_atual"]
            medicamentos_prescritos = form_consulta.cleaned_data[
                "medicamentos_prescritos"
            ]
            exames_prescritos = form_consulta.cleaned_data["exames_prescritos"]
            consulta_nova = consulta.ConsultaPet(
                pet=pet,
                motivo_consulta=motivo_consulta,
                peso_atual=peso_atual,
                medicamento_atual=medicamento_atual,
                medicamentos_prescritos=medicamentos_prescritos,
                exames_prescritos=exames_prescritos,
            )
            consulta_service.cadastar_consulta(consulta_nova)
            return redirect("listar_pet_id", pet.id)
    else:
        form_consulta = consulta_forms.ConsultaPetForm()
    return render(
        request, "consultas/form_consulta.html", {"form_consulta": form_consulta}
    )


@login_required()
def listar_consulta_id(request, id):
    consulta = consulta_service.listar_consulta(id)
    return render(request, "consultas/lista_consulta.html", {"consulta": consulta})


@login_required()
def enviar_email_consulta(request, id):
    consulta = consulta_service.listar_consulta(id)
    pet_consulta = pet_service.listar_pet_id(consulta.pet.id)
    assunto = "Resumo da consulta do seu PET"
    html_conteudo = render_to_string(
        "consultas/consulta_email.html", {"consulta": consulta}
    )
    corpo_email = "Resumo da sua consulta"
    email_remetente = "dnetochaves@gmail.com"
    email_destino = [
        pet_consulta.dono.email,
    ]
    send_mail(
        assunto, corpo_email, email_remetente, email_destino, html_message=html_conteudo
    )

    return redirect("listar_consulta_id", id)

clientes/views/funcionario_views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.hashers import make_password
from django.shortcuts import render, redirect
from ..forms.funcionario_forms import FuncionarioForm
from ..entidades import funcionario
from ..services import funcionario_service
from django.contrib.auth.decorators import login_required



def listar_funcionarios(request):
    funcionarios = funcionario_service.listar_funcionarios()
    return render(
        request, "funcionarios/lista_funcionarios.html", {"funcionarios": funcionarios}
    )


def inserir_funcionario(request):
    if request.method == "POST":
        form_funcionario = FuncionarioForm(request.POST)
        if form_funcionario.is_valid():
            nome = form_funcionario.cleaned_data["nome"]
            nascimento = form_funcionario.cleaned_data["nascimento"]
            cargo = form_funcionario.cleaned_data["cargo"]
            username = form_funcionario.cleaned_data["username"]
            password = make_password(form_funcionario.cleaned_data["password1"])
            funcionario_novo = funcionario.Funcionario(
                nome=nome,
                nascimento=nascimento,
                cargo=cargo,
                username=username,
                password=password,
            )
            funcionario_service.cadastrar_funcionario(funcionario_novo)
            return redirect("listar_funcionarios")
    else:
        form_funcionario = FuncionarioForm()
    return render(
        request,
        "funcionarios/form_funcionario.html",
        {"form_funcionario": form_funcionario},
    )

clientes/views/pet_views.py
from django.shortcuts import render, redirect
from ..forms import pet_forms
from ..entidades import pet
from ..services import pet_service, cliente_service, consulta_service
from django.contrib.auth.decorators import login_required


@login_required()
def inserir_pet(request, id):
    if request.method == "POST":
        form_pet = pet_forms.PetForm(request.POST)
        dono = cliente_service.listar_cliente_id(id)
        if form_pet.is_valid():
            nome = form_pet.cleaned_data["nome"]
            nascimento = form_pet.cleaned_data["nascimento"]
            categoria = form_pet.cleaned_data["categoria"]
            cor = form_pet.cleaned_data["cor"]
            pet_novo = pet.Pet(
                dono=dono,
                nome=nome,
                nascimento=nascimento,
                categoria=categoria,
                cor=cor,
            )
            pet_service.cadastrar_pet(pet_novo)
            return redirect("listar_clientes")
    else:
        form_pet = pet_forms.PetForm()
    return render(request, "pets/form_pet.html", {"form_pet": form_pet})


@login_required()
def listar_pet_id(request, id):
    pet = pet_service.listar_pet_id(id)
    consultas = consulta_service.listar_consultas(id)
    return render(request, "pets/lista_pet.html", {"pet": pet, "consultas": consultas})


@login_required()
def editar_pet(request, id):
    pet_antigo = pet_service.listar_pet_id(id)
    form_pet = pet_forms.PetForm(request.POST or None, instance=pet_antigo)
    if form_pet.is_valid():
        dono = form_pet.cleaned_data["dono"]
        nome = form_pet.cleaned_data["nome"]
        cor = form_pet.cleaned_data["cor"]
        nascimento = form_pet.cleaned_data["nascimento"]
        categoria = form_pet.cleaned_data["categoria"]
        pet_novo = pet.Pet(
            dono=dono, nome=nome, cor=cor, nascimento=nascimento, categoria=categoria
        )
        pet_service.editar_pet(pet_antigo, pet_novo)
        return redirect("listar_pets")
    return render(request, "pets/form_pet.html", {"form_pet": form_pet})

clientes/templates/clientes/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      
      {% block title %}
        
      {% endblock title %}
        
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
  </head>
  <body>
    <header class="py-3 mb-3 border-bottom">
      <div class="container-fluid d-grid gap-3 align-items-center" style="grid-template-columns: 1fr 2fr;">
        <div class="dropdown">
          <a href="#" class="d-flex align-items-center col-lg-4 mb-2 mb-lg-0 link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
            <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="currentColor" class="bi bi-alexa" viewBox="0 0 16 16">
              <path d="M7.996 0A8 8 0 0 0 0 8a8 8 0 0 0 6.93 7.93v-1.613a1.06 1.06 0 0 0-.717-1.008A5.6 5.6 0 0 1 2.4 7.865 5.58 5.58 0 0 1 8.054 2.4a5.6 5.6 0 0 1 5.535 5.81l-.002.046-.012.192-.005.061a5 5 0 0 1-.033.284l-.01.068c-.685 4.516-6.564 7.054-6.596 7.068A7.998 7.998 0 0 0 15.992 8 8 8 0 0 0 7.996.001Z" />
            </svg>
          </a>
          <ul class="dropdown-menu text-small shadow">
            <li>
              <a class="dropdown-item active" href="#" aria-current="page">{{ user }}</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Inventory</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Customers</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Products</a>
            </li>
            <li>  
              <hr class="dropdown-divider" />
            </li>
            <li>
              <a class="dropdown-item" href="#">Reports</a>
            </li>
            <li>
              <a class="dropdown-item" href="#">Analytics</a>
            </li>
          </ul>
        </div>

        <div class="d-flex align-items-center">
          <form class="w-100 me-3" role="search">
            <input type="search" class="form-control" placeholder="Search..." aria-label="Search" />
          </form>

          <div class="flex-shrink-0 dropdown">
            <a href="#" class="d-block link-body-emphasis text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle" /></a>
            <ul class="dropdown-menu text-small shadow">
              <li>
                <a class="dropdown-item" href="#">New project...</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Settings</a>
              </li>
              <li>
                <a class="dropdown-item" href="#">Profile</a>
              </li>
              <li>
                <hr class="dropdown-divider" />
              </li>
              <li>
                <a class="dropdown-item" href="{% url 'deslogar_usuario' %}">Sign out</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>
    
    {% block content %}
      
    {% endblock content %}
      
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
  </body>
</html>

clientes/templates/clientes/confirma_exclusao.html
{% extends 'clientes/base2.html' %}
{% load meus_filtros %}
{% block title %}
  Exclussão de clientes
{% endblock %}

{% block content %}
  <div class="card">
    <div class="card-body">
      <div class="container">
        <div class="card">
          <div class="card-body">
            <h5>Nome: {{ cliente.nome }}</h5>
            <h5>Profissão: {{ cliente.profissao }}</h5>
            <h5>Data de Nascimento: {{ cliente.data_nascimento }}</h5>
            <h5>Email: {{ cliente.email }}</h5>
            <h5>CPF: {{ cliente.cpf }}</h5>

            <form method="POST">
              {% csrf_token %}
              <button class="btn btn-danger" type="submit">Remover</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

clientes/templates/clientes/form_cliente.html
{% extends 'clientes/base2.html' %}
{% load meus_filtros %}
{% block title %}
  Cadastro de clientes
{% endblock %}

{% block content %}
  <div class="card">
    <div class="card-body">
      <form action="" method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">Nome</label>
          {{ form_cliente.nome|addclass:'form-control' }}
        </div>
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">data_nascimento</label>
          {{ form_cliente.data_nascimento.errors }}
          {{ form_cliente.data_nascimento|addclass:'form-control' }}
        </div>
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">email</label>
          {{ form_cliente.email.errors }}
          {{ form_cliente.email|addclass:'form-control' }}
        </div>
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">cpf</label>
          {{ form_cliente.cpf.errors }}
          {{ form_cliente.cpf|addclass:'form-control' }}
        </div>
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">profissao</label>
          {{ form_cliente.profissao.errors }}
          {{ form_cliente.profissao|addclass:'form-control' }}
        </div>
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">endereco</label>
          {{ form_endereco.estado.errors }}
          {{ form_endereco.estado|addclass:'form-control' }}
        </div>
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">cidade</label>
          {{ form_endereco.cidade.errors }}
          {{ form_endereco.cidade|addclass:'form-control' }}
        </div>
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">estado</label>
          {{ form_endereco.estado.errors }}
          {{ form_endereco.estado|addclass:'form-control' }}
        </div>
        <div class="mb-3">
          <label for="exampleFormControlInput1" class="form-label">rua</label>
          {{ form_endereco.rua.errors }}
          {{ form_endereco.rua|addclass:'form-control' }}
        </div>
        <hr>
        <input type="submit" class="btn btn-primary" name="Cadastrar" />
      </form>
    </div>
  </div>
{% endblock %}

clientes/templates/clientes/lista_cliente.html
{% extends 'clientes/base2.html' %}
{% load meus_filtros %}
{% block title %}
  Lista de
{% endblock %}

{% block content %}
  <div class="card">
    <div class="card-body">
      <div class="container text-center">
        <div class="row">
          <div class="col">
            <div class="card">
              <div class="card-header">id - {{ cliente.nome }}</div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">{{ cliente.email }}</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <table class="table">
      <thead>
        <h3>Seus Pets</h3>
        <tr>
          <th scope="col">id</th>
          <th scope="col">nome</th>
          <th scope="col">categoria</th>
          <th scope="col">cor</th>
          <th scope="col">Ação</th>
        </tr>
      </thead>
      <tbody>
        {% for pet in pets %}
          <tr>
            <th scope="row">{{ pet.id }}</th>
            <td>
              {{ pet.nome }}
            </td>
            <td>{{ pet.get_categoria_display }}</td>
            <td>{{ pet.get_cor_display }}</td>
            <td>
              <a class="btn btn-primary" href="{% url 'listar_pet_id' pet.id %}">Consultas</a>
              <a class="btn btn-primary" href="{% url 'cadastrar_consulta' pet.id %}">Cadastrar Consulta</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <table class="table">
      <thead>
        <h3>Consultas dos Pets</h3>
        <tr>
          <th scope="col">id</th>
          <th scope="col">pet</th>
          <th scope="col">motivo_consulta</th>
          <th scope="col">peso_atual</th>
          <th scope="col">medicamento_atual</th>
          <th scope="col">medicamentos_prescritos</th>
          <th scope="col">exames_prescritos</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        {% for consulta in consultas %}
          <tr>
            <th scope="row">{{ consulta.id }}</th>
            <td>
              {{ consulta.pet.nome }}
            </td>
            <td>{{ consulta.motivo_consulta }}</td>
            <td>{{ consulta.peso_atual }}</td>
            <td>{{ consulta.medicamento_atual }}</td>
            <td>{{ consulta.medicamentos_prescritos }}</td>
            <td>{{ consulta.exames_prescritos }}</td>
            <td><a class="btn btn-primary" href="{% url 'listar_consulta_id' consulta.id %}">Ver</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}